const gitaquotes = [
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“Even the wise are confused about what is action and what is inaction.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“Those who are motivated only by desire for the fruits of their actions are miserable, for they are constantly anxious about the results of what they do.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“Change is the law of the universe. You can become a millionaire or a pauper in an instant.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“There never was a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“For the soul, there is neither birth nor death. Nor, having once been, does it ever cease to be.”",
        "“He is unborn, eternal, ever-existing, undying, and primeval. He is not slain when the body is slain.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“He who has no attachments can really love others, for his love is pure and divine.”",
        "“All that we are is the result of what we have thought. The mind is everything. What we think, we become.”",
        "“The soul is neither born, nor does it die.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“The embodied soul is eternal in existence, indestructible, and infinite, only the material body is factually perishable, therefore fight O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“There never was a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.”",
        "“You came empty handed, and you will leave empty handed.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend or enemy.”",
        "“The meaning of Karma lies in the intention. The intention behind the action is what matters.”",
        "“The happiness that arises from the serenity of one's own mind, which leads to the end of suffering, is like poison at first but like nectar in the end.”",
        "“A gift is pure when it is given from the heart to the right person at the right time and place, without expecting anything in return.”",
        "“He who is temperate in his habits of eating, sleeping, working and recreation can mitigate all material pains by practicing the yoga system.”",
        "“Change is the law of the universe. You can be a millionaire, or a pauper in an instant.”",
        "“You have the right to perform your prescribed duty, but you are not entitled to the fruits of your actions.”",
        "“When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.”",
        "“The soul is neither born, nor does it die.”",
        "“The mind acts like an enemy for those who do not control it.”",
        "“Perform your obligatory duty, because action is indeed better than inaction.”",
        "“Set your heart upon your work, but never on its reward.”",
        "“The soul is neither born, nor does it die.”",
        "“The power of God is with you at all times; through the activities of mind, senses, breathing, and emotions; and is constantly doing all the work using you as a mere instrument.”",
        "“No one who does good work will ever come to a bad end, either here or in the world to come.”",
        "“It is better to live your own destiny imperfectly than to live an imitation of somebody else's life with perfection.”",
        "“The wise grieve neither for the living nor the dead.”",
        "“The embodied soul is eternal, indestructible, and infinite, while the material body is perishable. Therefore, fight, O Arjuna.”",
        "“Yoga is the journey of the self, through the self, to the self.”",
        "“The soul can never be cut into pieces by any weapon, nor can it be burned by fire, moistened by water, or withered by the wind.”",
        "“You came empty-handed, and you will leave empty-handed.”",
        "“The mind is restless and difficult to restrain, but it can be subdued by practice.”",
        "“A person can rise through the efforts of their own mind; self-discipline or self-destruction happens as a result of their own mind. We are each our own friend.”"
      
];

let previousIndex = -1; // Initialize with an index that is out of bounds

function updateQuote() {
    let randomIndex = Math.floor(Math.random() * gitaquotes.length);
    // Generate a new random index until it's different from the previous index
    while (randomIndex === previousIndex) {
        randomIndex = Math.floor(Math.random() * gitaquotes.length);
    }
    previousIndex = randomIndex; // Update the previous index
    document.getElementById("dquote").textContent = gitaquotes[randomIndex];
}

document.getElementById("changequote").addEventListener("click", updateQuote);

updateQuote(); // Display a random quote by default
